version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git

jobs:
  build:
    docker: 
      - build: .
    steps:
      - checkout
      - run: docker build -t frontend .
      - run: docker run -d -p 5000:5000 frontend
