version: 2.1

workflows:
  heroku_deploy:
    jobs:
      - build
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t test .
      - run: heroku container:login
      - run: heroku container:push test/web
      - run: heroku container:release test/web
  
