version: 2.1

workflows:
  heroku_deploy:
    jobs:
      - build
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker pull devopsdockeruh/heroku-example:latest
      - run: heroku container:login
      - run: heroku container:push devopsdockeruh/heroku-example
      - run: heroku container:release devopsdockeruh/heroku-example
