version: 2.1

workflows:
  heroku_deploy:
    jobs:
      - build
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t test .
      - run: docker login --email=_ --username=_ --password=$HEROKU_TOKEN registry.heroku.com
      - run: docker tag test:latest registry.heroku.com/test/web
      - run: docker push registry.heroku.com/test/web
