version: 2.1

workflows:
  heroku_deploy:
    jobs:
      - build
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build .
      - run: heroku container:login
      - run: heroku container:push web
      - run: heroku container:release web
  
