version: 2.1

workflows:
  heroku_deploy:
    jobs:
      - build
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t frontend .
      - run: docker container:push web
      - run: docker container:release web
